### PR TITLE
spell-check and re-word beginning of covid-19 dungeon for readability

### PR DESCRIPTION
**Pull request by Gborgman05**
#112 fixed spelling. The route had an option to just "go into the dungeon" which didn't make sense if you were chained to a post, but another route has you break the chain after getting strong, so I don't know what we should do.

### CODE REVIEW

**Review by paulsonjpaul — CHANGES_REQUESTED** [review]
Good. But, as you have changed the _go into dungeon_ text, you may need to link it to another document (`3` maybe?).

Please fix the linking.

**Comment by Gborgman05** [comment]
Fixed linking issue that @paulsonjpaul spotted, then resolved merge conflict with #123 that fixed WIP link

**Comment by paulsonjpaul** [comment]
Good. Now it makes sense. Add some emojis 😉

**Comment by ming-tsai** [comment]
Hi @Gborgman05 and @paulsonjpaul,
Any update?

**Comment by Gborgman05** [comment]
@ming-tsai , @paulsonjpaul , just added some emojis to spice up the route. I'd love any feedback!

**Review by ming-tsai — APPROVED** [review]

**Comment by ming-tsai** [comment]
Nice work @Gborgman05

**Pull request merged**
