### PR TITLE
added another line to 3/2-2.md

### PR DESCRIPTION
**Pull request by YungBryanX**
added a 2nd line after the goblins kill you in 3/2-2. The emojis in my line render in my forked repository, but it seems like they won't in this comment for some reason.

```diff
You go to the backyard of your house 🏡 and opens the door 🚪 slightly. Suddenly, two goblins 👺👺 emerged from inside and finished you with their sharp sword ⚔️.

+ As you lay they, dying :skull: , you wonder what life would have been like if you made different decisions :thought_balloon: ...

THE END! 🎬

[🔄 Restart the game](../begin-journey.md)
```

### CODE REVIEW

**Review by paulsonjpaul — CHANGES_REQUESTED** [review]
Good job @YungBryanX. The reason the emojis are not showing is that you need to copy and paste emojis and not type them in markdown format.

You can go to [Emojipedia](https://emojipedia.org/), search for the preferred emoji, and copy and paste it into the file. That will work.

**Comment by YungBryanX** [comment]
Hey @paulsonjpau, i added the emojis from emojipedia as recommended. You can see my additional commit above, thanks for the resource.

```diff
You go to the backyard of your house 🏡 and opens the door 🚪 slightly. Suddenly, two goblins 👺👺 emerged from inside and finished you with their sharp sword ⚔️.

+ As you lay they, dying 💀, you wonder what life would have been like if you made different decisions 💭 ...

THE END! 🎬

[🔄 Restart the game](../begin-journey.md) 
```

**Comment by paulsonjpaul** [comment]
Let's wait for @ming-tsai to merge this

**Review by ming-tsai — APPROVED** [review]
Hi @YungBryanX,
Nice work and welcome to our team 🎉🎉🎉

**Pull request merged**
