### PR TITLE
Update wip.md

### PR DESCRIPTION
**Pull request by Codely-F**
I have updated the link
from `../../../README.md#contribution-guidelines` to` ../../README.md#contribution-guidelines`

Addresses #115

### CODE REVIEW

**Review by paulsonjpaul — APPROVED** [review]
Great job!

**Comment by paulsonjpaul** [comment]
Please check this @ming-tsai

**Comment by paulsonjpaul** [comment]
@Codely-F can you please edit your first post and add `Addresses #115`?

**Comment by Codely-F** [comment]
Done with editing the post.

**Review by Arsenic-ATG — APPROVED** [review]
@ming-tsai I would recommend going for a [squash merge](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/about-pull-request-merges#squash-and-merge-your-pull-request-commits) on this one as all three commits are doing the same task and it is better to perform one single commit doing so to keep the development tree clean.

**Comment by ming-tsai** [comment]
> @ming-tsai I would recommend going for a [squash merge](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/about-pull-request-merges#squash-and-merge-your-pull-request-commits) on this one as all three commits are doing the same task and it is better to perform one single commit doing so to keep the development tree clean.

Done

**Comment by ming-tsai** [comment]
Hi @Codely-F, nice work and welcome to our team

**Pull request merged**
