### PR TITLE
chore(sci-fi): add more room and floors

### PR DESCRIPTION
**Pull request by Manas-Tiwari**
Added floor-1 with room i.e. 1-A & 1-B & both rooms are extending to 2 sub rooms i.e. 1-A1 1-A2 and 1-B1 1-B2.
NOTE : 1-B1 and 1-B2 are under development.

### CODE REVIEW

**Review by ming-tsai — CHANGES_REQUESTED** [review]
Hi @Manas-Tiwari,
Please make the below changed:
1. Use the markdown [unordered lists](https://www.markdownguide.org/basic-syntax/#unordered-lists)
Example:
```md
- [Option 1](./example1)
- [Option 2](./example2)
```
2. You could create the WIP floor like this one [COVID-19 WIP](https://github.com/MakeContributions/markdown-dungeon/blob/master/english/covid-19/WIP.md), and remove all floors that only has this `_under Development_`

**Comment by manas0411** [comment]
Ok, I get it. I will take a look at requested changes.
Thanks.

**Comment by Manas-Tiwari** [comment]
Ya I get it. I will take a look at this. Thanks for the suggestions.

**Comment by Manas-Tiwari** [comment]
hello @ming-tsai, as per your suggested changes,
the ol(s) are changed to ul(s) and i have added WIP floor where work is in progress.

**Comment by ming-tsai** [comment]
> hello @ming-tsai, as per your suggested changes,
> the ol(s) are changed to ul(s) and i have added WIP floor where work is in progress.

Hi @Manas-Tiwari,
- Could you unify all WIP file?
- You could create a dead line like this [one](https://github.com/MakeContributions/markdown-dungeon/blob/master/english/normal-dungeon/1/1.md)

**Comment by Manas-Tiwari** [comment]
Yeah sure. I think that's a good idea.

**Comment by Manas-Tiwari** [comment]
hi ming, as you said, i have added a common WIP file along with a end-of-story file(dead link) wherever i felt the necessity.

**Review by ming-tsai — DISMISSED** [review]

**Review by ming-tsai — APPROVED** [review]

**Comment by Manas-Tiwari** [comment]
thanks for merging. 👍🏽

**Pull request merged**
