### PR TITLE
 Translation into other languages: Portuguese - Brazil

### PR DESCRIPTION
**Pull request by Kouthk**
The first module of the game was translated. 😃 
 (Hacktoberfest, pls)

### CODE REVIEW

**Comment by ming-tsai** [comment]
Hi @Kouthk, this is on WIP? Because some of the room is not translate to portuguese

**Review by ming-tsai — APPROVED** [review]
Hi @Kouthk, thanks for your translate it and welcome to our team

**Comment by Kouthk** [comment]
@ming-tsai, thanks!. =)
I will translate the remaining "Modules". could you put a [hacktoberfest-accepted](https://hacktoberfest-assets.nyc3.cdn.digitaloceanspaces.com/hacktoberfest-label-add-gif-min.gif) tag?

**Comment by ming-tsai** [comment]
@Kouthk,
Please configure your GitHub with the email that is committing or the other way around

**Pull request merged**
