### PR TITLE
feat: add escape-madrid

### PR DESCRIPTION
**Pull request by crisjumbo**
I want to link this PR to the Oktoberfest issue but I am quite lost with it. I will try to read more docs about the topic.

About the dungeon: I added the escape-Madrid dungeon. I followed the guidelines about the file-structure. Thank you in advance for this opportunity to add value to the community through code.
Fixes # #128

### CODE REVIEW

**Review by ming-tsai — CHANGES_REQUESTED** [review]
Hi @srcristofher,
Please fix sepelling error
image

**Comment by ming-tsai** [comment]
> I want to link this PR to the Oktoberfest issue but I am quite lost with it. I will try to read more docs about the topic.
> 
> About the dungeon: I added the escape-Madrid dungeon. I followed the guidelines about the file-structure. Thank you in advance for this opportunity to add value to the community through code. Fixes # #128

Please check if now is appearing?

**Review by ming-tsai — COMMENTED** [review]
Question the one which goes home could go to `WIP`?
Example [file](https://github.com/MakeContributions/markdown-dungeon/blob/master/english/covid-19/WIP.md)

**Comment by srcristofher** [comment]
> WIP

I do not understand. Did you mean if my repo is outdated?

**Comment by ming-tsai** [comment]
> > WIP
> 
> I do not understand. Did you mean if my repo is outdated?

No, I mean if this repo is end of edition?
If not please add `WPI.md` for dungeon and all files that reference to `Go to home` please refer the `WIP.md`

**Review by ming-tsai — CHANGES_REQUESTED** [review]
Hi @srcristofher,
I add suggestions for this pull request:
1. If the room has options it is not allowed add restart the game
2. The `WIP.md` is using when you have an option and you don't have any room to point it
3. When is on the end of the path must use `restart the game` and referring the `begin-journey.md`

**Comment by ming-tsai** [comment]
Hi @srcristofher,
Any updated?

**Comment by ming-tsai** [comment]
Hi @srcristofher,
Any update about this pull request?

**Pull request closed without merging**
