### PR TITLE
Added new dungeon

### LINKED ISSUE #103: Add more dungeons, rooms or floors - Part 3
It'd be awesome to have a lot of the dungeons, rooms, or floors, so the game could be more fun 😜

🐞 Problem
Currently, we have only a bunch of dungeons, rooms, or floors in the project

🎯 Goal
Have a lot of dungeons, rooms, or floors from the diverse games.

💡 Possible solutions
Add new a new dungeon, rooms, or floors.

**How to make it?**
Check out [Contribution Guidelines](https://github.com/MakeContributions/markdown-dungeon#contribution-guidelines)

📋 Steps to solve the problem

1. Comment below about what you've started working on.
2. Add, commit, push your changes
3. Submit a pull request and add this in comments - Addresses #
4. Ask for a review in the comments section of the pull request
5. Celebrate your contribution to this project 🎉 

> This issue will close every 10 contributions for adding new room(s) or floor(s)

### PR DESCRIPTION
**Pull request by FukurouMakoto**
Added a new dungeon, a castle that the player can access from 3-1.
It has three rooms initially along with multiple floors. Second floor is still in progress. 
Let me know if everything is okay before I continue working on this. 
Fixes #103

### CODE REVIEW

**Comment by paulsonjpaul** [comment]
I like it. You have a special skill of storytelling which I lack.

Add some emojis to the story! 😃 👍

**Comment by paulsonjpaul** [comment]
One more important thing I noticed. Your PR has some merge conflicts. The reason is because there is already a floor named `7` in the `normal-dungeon`, and that was added by me in the latest PR #108. Maybe the reason you didn't notice it is because you did not make your fork up to date.

Maybe renaming the folder name might fix the issue, I think. @ming-tsai, any other ways to fix this?

**Comment by FukurouMakoto** [comment]
> One more important thing I noticed. Your PR has some merge conflicts. The reason is because there is already a floor named `7` in the `normal-dungeon`, and that was added by me in the latest PR #108. Maybe the reason you didn't notice it is because you did not make your fork up to date.
> 
> Maybe renaming the folder name might fix the issue, I think. @ming-tsai, any other ways to fix this?


So THAT's what it is! I was wondering what was causing that!
That's weird because I made sure to make a pull before I started working; I must've accidentally pulled from my fork instead of the main branch. 
I'll try renaming the files and seeing if that works!

**Comment by ming-tsai** [comment]
Yes @paulsonjpaul

**Comment by paulsonjpaul** [comment]
> > One more important thing I noticed. Your PR has some merge conflicts. The reason is because there is already a floor named `7` in the `normal-dungeon`, and that was added by me in the latest PR #108. Maybe the reason you didn't notice it is because you did not make your fork up to date.
> > Maybe renaming the folder name might fix the issue, I think. @ming-tsai, any other ways to fix this?
> 
> So THAT's what it is! I was wondering what was causing that!
> That's weird because I made sure to make a pull before I started working; I must've accidentally pulled from my fork instead of the main branch.
> I'll try renaming the files and seeing if that works!

If you want to make your fork up to date, this video will help:
https://www.youtube.com/watch?v=deEYHVpE1c8&t=26s

**Comment by FukurouMakoto** [comment]
> > > One more important thing I noticed. Your PR has some merge conflicts. The reason is because there is already a floor named `7` in the `normal-dungeon`, and that was added by me in the latest PR #108. Maybe the reason you didn't notice it is because you did not make your fork up to date.
> > > Maybe renaming the folder name might fix the issue, I think. @ming-tsai, any other ways to fix this?
> > 
> > 
> > So THAT's what it is! I was wondering what was causing that!
> > That's weird because I made sure to make a pull before I started working; I must've accidentally pulled from my fork instead of the main branch.
> > I'll try renaming the files and seeing if that works!
> 
> If you want to make your fork up to date, this video will help:
> https://www.youtube.com/watch?v=deEYHVpE1c8&t=26s

Thanks for the link; think I have everything properly synced now

**Comment by ming-tsai** [comment]
Hi @FukurouMakoto, are you merging correctly? Because some of your file has this
```
<======== head
...
=============
```
 
This normal show when you have merging conflict on the file and don't solve it, maybe you could move your part to another floor

**Comment by FukurouMakoto** [comment]
> Hi @FukurouMakoto, are you merging correctly? Because some of your file has this
> 
> ```
> <======== head
> ...
> =============
> ```
> 
> This normally is showing when you have merging conflict on the file and doesn't solve it, maybe you could move your part to another floor

To another floor as in rename the folders? I can do that if that's what you mean.

**Comment by ming-tsai** [comment]
Yes

**Comment by ming-tsai** [comment]
> > Hi @FukurouMakoto, are you merging correctly? Because some of your file has this
> > 
> > ```
> > <======== head
> > ...
> > =============
> > ```
> > 
> > This normally is showing when you have merging conflict on the file and doesn't solve it, maybe you could move your part to another floor
> 
> To another floor as in rename the folders? I can do that if that's what you mean.

Yes

**Comment by FukurouMakoto** [comment]
> > > Hi @FukurouMakoto, are you merging correctly? Because some of your file has this
> > > ```
> > > <======== head
> > > ...
> > > =============
> > > ```
> > > 
> > > 
> > > This normally is showing when you have merging conflict on the file and doesn't solve it, maybe you could move your part to another floor
> > 
> > 
> > To another floor as in rename the folders? I can do that if that's what you mean.
> 
> Yes

Okay done. Let me know if that worked.

**Comment by ming-tsai** [comment]
@FukurouMakoto the next floor is **8** please rename the folder **9** to **8**

**Comment by FukurouMakoto** [comment]
> @FukurouMakoto the next floor is **8** please rename the folder **9** to **8**

To make sure, **8** was what the folder was named originally, and was causing the errors before as seen below:

> > > Hi @FukurouMakoto, are you merging correctly? Because some of your file has this
> > > ```
> > > <======== head
> > > ...
> > > =============
> > > ```
> > > 
> > > 
> > > This normally is showing when you have merging conflict on the file and doesn't solve it, maybe you could move your part to another floor
> > 
> > 
> > To another floor as in rename the folders? I can do that if that's what you mean.
> 
> Yes

What should I rename it to then?

**Comment by ming-tsai** [comment]
Ok, keep it on 9, but please delete folder `.vscode`

**Comment by paulsonjpaul** [comment]
I think the `.vscode` file is created by VS Code Live Server Extension. It had happened to me also.

**Comment by ming-tsai** [comment]
Ok

**Review by ming-tsai — APPROVED** [review]
Approved, nice work @FukurouMakoto

**Review by paulsonjpaul — COMMENTED** [review]
Good job @FukurouMakoto as always. You have a special talent in this. Keep it up 👍

**Pull request merged**
