### PR TITLE
chore(COVID-19): add new room for dungeon

### PR DESCRIPTION
**Pull request by yeelong1234**
Hi I had a new room for covid-19 dungeon, please help me to review it thanks

### CODE REVIEW

**Review by ming-tsai — CHANGES_REQUESTED** [review]
Hi @yeelong1234,
Please add an option that could be redirect to this page?

**Comment by yeelong1234** [comment]
Hi @ming-tsai 
The option "Vampire" in the 3-CAA.md file will redirect to this page. Can you please check about it?

**Comment by ming-tsai** [comment]
Hi @yeelong1234,
This is the code for `3-CAA.md` and it is not redirecting to the new page, it redirects to `WIP.md`.
```md
You found a few small pills💊💊💊 at a dark corner 🌑. Each pill has a label 🏷️ on it. 

***Which pill 💊 will you choose?***

- [🧛Vampire](../WIP.md)
- [🦇Bat Monster](../WIP.md)
- [🤖Transformer](../WIP.md)
```

**Comment by ming-tsai** [comment]
Hi @yeelong1234,
Any update about this?

**Pull request closed without merging**
