### PR TITLE
More paths for dungeon

### LINKED ISSUE #103: Add more dungeons, rooms or floors - Part 3
It'd be awesome to have a lot of the dungeons, rooms, or floors, so the game could be more fun 😜

🐞 Problem
Currently, we have only a bunch of dungeons, rooms, or floors in the project

🎯 Goal
Have a lot of dungeons, rooms, or floors from the diverse games.

💡 Possible solutions
Add new a new dungeon, rooms, or floors.

**How to make it?**
Check out [Contribution Guidelines](https://github.com/MakeContributions/markdown-dungeon#contribution-guidelines)

📋 Steps to solve the problem

1. Comment below about what you've started working on.
2. Add, commit, push your changes
3. Submit a pull request and add this in comments - Addresses #
4. Ask for a review in the comments section of the pull request
5. Celebrate your contribution to this project 🎉 

> This issue will close every 10 contributions for adding new room(s) or floor(s)

### PR DESCRIPTION
**Pull request by FukurouMakoto**
fixes #103. 
Continued work on my dungeon

### CODE REVIEW

**Comment by FukurouMakoto** [comment]
> Hi @FukurouMakoto are you checking the comments?

Yeah why whats up?

**Comment by ming-tsai** [comment]
Sorry, because you didn't answer me, so I was thinking you didn't see these comments

**Comment by ming-tsai** [comment]
Hi @FukurouMakoto,
Any update?

**Comment by FukurouMakoto** [comment]
> Hi @FukurouMakoto,
> Any update?

I'm sorry, what comment? 
I think maybe I'm missing something cuz i was just waiting to get this pull request approved.

**Review by ming-tsai — APPROVED** [review]

**Pull request merged**
