### PR TITLE
docs(translations): add french README.md

### PR DESCRIPTION
**Pull request by ThierryRakotomanana**
Hi! I am new to the open source contribution and, here I want to add a French version to the readme file content in the "translations" directory
Pull request: #229

### CODE REVIEW

**Review by ming-tsai — CHANGES_REQUESTED** [review]
Hi @ThierryRakotomanana,
Some suggestions for the pull request:
- Could you please add this file on the index `README.md` that is on the translations folder?
- Please check the reference link on the folder, it is not working, you should use relative link to refer the file or directory.

**Comment by ming-tsai** [comment]
Hi @ThierryRakotomanana,
Do you need any help?

**Comment by ThierryRakotomanana** [comment]
Hi, @ming-tsai, this Pull request is closed and i made another one if it does not bother you

**Comment by ThierryRakotomanana** [comment]
The number of the Pull Request
Pull Request #230

**Pull request merged**
